global:
  scrape_interval: 5s 
  evaluation_interval: 5s

scrape_configs:
  - job_name: "botanical-monitoring-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["ml-api:8000"]
        labels:
          service: "iris-inference-api"
          environment: "production"
          variant: "v3-monitored"

  - job_name: "prometheus-internal"
    static_configs:
      - targets: ["localhost:9090"]